name: Docker Image CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --tag airnominal/backend:$(date '+%Y%m%d%H%M%S')

  release:
    name: Release Docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Extract the Docker metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/airnominal/backend
          tags: |
            type=raw,value={{date 'YYYYMMDDhhmmss'}}
            type=raw,value=latest

      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: "ghcr.io"

      - name: Build and release the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
